version: "3"
services:
  ethereum:
    image: ghcr.io/foundry-rs/foundry:v1.0.0
    command: "'anvil --silent -p 8545 --host 0.0.0.0 --chain-id 31337'"

  aztec:
    image: aztecprotocol/aztec:${AZTEC_DOCKER_TAG:-latest}
    environment:
      ETHEREUM_HOST: http://ethereum:8545
      CHAIN_ID: 31337
      ARCHIVER_POLLING_INTERVAL_MS: 50
      P2P_BLOCK_CHECK_INTERVAL_MS: 50
      SEQ_TX_POLLING_INTERVAL_MS: 50
      WS_BLOCK_CHECK_INTERVAL_MS: 50
      PXE_BLOCK_POLLING_INTERVAL_MS: 50
      ARCHIVER_VIEM_POLLING_INTERVAL_MS: 500
    depends_on:
      - ethereum

  test:
    build:
      context: ../
      dockerfile: ./docs/Dockerfile.test
    tty: true
    stdin_open: true
